### ISSUE TITLE
ESP32-S2 Windowns 10 Drivers

### ISSUE THREAD

**Issue by reletobg** [vernonet/ESP32_PRJ#1]
I have tried the USB Mic example, but the board is not recognized from Win10. What kind of drivers you are using or recommend?

**Comment by vernonet** [comment]
You need to use a standard driver (included with Windows) - manufacturer "Microsoft"  model "USB Audio 2.0". Install it manually.
....Library "tinyusb" needs to be used  only from my project, the original library one will not work.

![4747474](https://github.com/vernonet/ESP32_PRJ/assets/49722354/f8abb078-917c-44bc-9ad4-32dc86816996)

**Comment by vernonet** [comment]
It's strange, but in the English version of Win 10 Pro the driver has a different name - "Audio Endpoint".
https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/usb-2-0-audio-drivers
...The microphone appears in the device manager in two sections - "Audio inputs and outputs" and "Sound, video and game controllers" and accordingly the names of the drivers are different (audio endpoint and usbaudio 2.0).

![aud_endp](https://github.com/vernonet/ESP32_PRJ/assets/49722354/f385bbfd-2550-45e0-b472-1556a6890dec)
